group: travis_latest
language: python
cache: pip
matrix:
  include:
    - python: "2.7"
    - python: "3.4.3"  # See README.md
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
install: pip install tox-travis
script: tox
